title: QILOMBO
description: Curated Tech Center By Bobby-Digital
url: "https://www.qilombo.tech"
baseurl: ""

# This tells Jekyll to look for your Notion articles in the 'content' folder
collections:
  content:
    output: true
    permalink: /:slug/

# Exclude node_modules so the build doesn't crash
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
