title: QILOMBO
description: Curated Tech Center By Bobby-Digital
url: "https://www.qilombo.tech"
baseurl: ""

# 1. FIX: Ensure future posts are built
future: true

collections:
  content:
    output: true
    permalink: /:slug/

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - vendor
